name: ace-t-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - pydantic=2.10.3
  - python-dotenv
  - python-multipart
  - email-validator
  - typer
  - starlette
  - jinja2
  - rich
  - httpx
  - watchfiles
  - pip
  - wheel
  - tk
  - scrapy
  - itemadapter
  - requests
  - pandas
  - matplotlib
  - seaborn
  - alembic
  - pytest
  - pyyaml
  - twisted
