name: ace-t-env
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - anyio=4.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - click=8.1.7
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - fastapi=0.115.6
  - fastapi-cli=0.0.5
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.0.1
  - idna=3.10
  - jinja2=3.1.4
  - libexpat=2.6.4
  - libffi=3.4.4
  - libsqlite=3.45.2
  - libuv=1.49.2
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.4
  - openssl=3.4.0
  - pip=24.3.1
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.18.0
  - python=3.11.8
  - python-dotenv=1.0.1
  - python-multipart=0.0.19
  - python_abi=3.11
  - pyyaml=6.0.2
  - readline=8.2
  - rich=13.9.4
  - setuptools=75.1.0
  - shellingham=1.5.4
  - sniffio=1.3.1
  - sqlite=3.45.2
  - starlette=0.41.3
  - tk=8.6.13
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - uvloop=0.21.0
  - watchfiles=1.0.0
  - websockets=14.1
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.3.1
