name: ace-t-env
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - anyio=4.7.0
  - appdirs=1.4.4
  - attrs=24.2.0
  - automat=24.8.1
  - bcrypt=4.2.1
  - beautifulsoup4=4.12.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - constantly=15.1.0
  - cryptography=44.0.0
  - cssselect=1.2.0
  - defusedxml=0.7.1
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - fastapi=0.115.6
  - fastapi-cli=0.0.5
  - filelock=3.16.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.0.1
  - hyperlink=21.0.0
  - icu=75.1
  - idna=3.10
  - incremental=24.7.2
  - itemadapter=0.10.0
  - itemloaders=1.3.2
  - jinja2=3.1.4
  - jmespath=1.0.1
  - libcxx=19.1.5
  - libexpat=2.6.4
  - libffi=3.4.4
  - libiconv=1.17
  - liblzma=5.6.3
  - libsqlite=3.45.2
  - libuv=1.49.2
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lxml=5.3.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.4
  - openssl=3.4.0
  - packaging=24.2
  - parsel=1.9.1
  - pip=24.3.1
  - protego=0.3.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydispatcher=2.0.5
  - pygments=2.18.0
  - pyopenssl=24.3.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-dotenv=1.0.1
  - python-multipart=0.0.19
  - python_abi=3.11
  - pyyaml=6.0.2
  - queuelib=1.7.0
  - readline=8.2
  - requests=2.32.3
  - requests-file=2.1.0
  - rich=13.9.4
  - scrapy=2.12.0
  - service-identity=24.2.0
  - service_identity=24.2.0
  - setuptools=75.1.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.2
  - starlette=0.41.3
  - tk=8.6.13
  - tldextract=5.1.3
  - twisted=24.11.0
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - uvloop=0.21.0
  - w3lib=2.2.1
  - watchfiles=1.0.0
  - websockets=14.1
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zope.interface=7.2
  - zstandard=0.23.0
  - zstd=1.5.6
